development:
  strategy: oauth
  oauth_consumer_key: <%= DONTPLAGIARIZEUS_TWITTER_CONSUMER_KEY %>
  oauth_consumer_secret: <%= DONTPLAGIARIZEUS_TWITTER_CONSUMER_SECRET %>
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 30 # days
  oauth_callback: "http://127.0.0.1:3000/oauth_callback"
test:
  strategy: oauth
  oauth_consumer_key: <%= DONTPLAGIARIZEUS_TWITTER_CONSUMER_KEY %>
  oauth_consumer_secret: <%= DONTPLAGIARIZEUS_TWITTER_CONSUMER_SECRET %>
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 30 # days
  oauth_callback: "http://127.0.0.1:3000/oauth_callback"
production:
  strategy: oauth
  oauth_consumer_key: <%= DONTPLAGIARIZEUS_TWITTER_CONSUMER_KEY %>
  oauth_consumer_secret: <%= DONTPLAGIARIZEUS_TWITTER_CONSUMER_SECRET %>
  authorize_path: "/oauth/authenticate"
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 30 # days
  oauth_callback: "http://dontplagiarizeus.heroku.com/oauth_callback"
