development:
  strategy: oauth
  oauth_consumer_key: aQIEX6RUh0ZGk6DUZ57rA
  oauth_consumer_secret: Vuy50Dk8dacha3dr8gYdufnsWXpXlwvE1Ril2XlY
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 30 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
test:
  strategy: oauth
  oauth_consumer_key: aQIEX6RUh0ZGk6DUZ57rA
  oauth_consumer_secret: Vuy50Dk8dacha3dr8gYdufnsWXpXlwvE1Ril2XlY
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 30 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
production:
  strategy: oauth
  oauth_consumer_key: aQIEX6RUh0ZGk6DUZ57rA
  oauth_consumer_secret: Vuy50Dk8dacha3dr8gYdufnsWXpXlwvE1Ril2XlY
  authorize_path: "/oauth/authenticate"
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 30 # days
  oauth_callback: "http://dontplagiarizeus.heroku.com/oauth_callback"
